name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - actions

jobs:
  test-node-10:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Repository checkout
    - uses: actions/setup-node@v2
      name: Node 10 Setup
      with:
        node-version: '10'
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm test

  test-node-12:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Repository checkout
    - uses: actions/setup-node@v2
      name: Node 12 Setup
      with:
        node-version: '12'
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm test

  test-node-14:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Repository checkout
    - uses: actions/setup-node@v2
      name: Node 14 Setup
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm test

  test-node-16:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Repository checkout
    - uses: actions/setup-node@v2
      name: Node 16 Setup
      with:
        node-version: '16'
    - name: Install dependencies
      run: npm install
    - name: Build and test
      run: npm test
