name: sast

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - actions

jobs:
  security:
    name: security
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Horusec
      run: curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/master/deployments/scripts/install.sh | bash -s latest
    - name: Run Horusec
      run: horusec start -p . -e true
